// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuazxpefwdifgxmerntj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51YXp4cGVmd2RpZmd4bWVybnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTE2NzksImV4cCI6MjA1ODcyNzY3OX0.g_GAfIc-KzrrgAJejctRs_XZWfw8jEvbBjGbM1HTpgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);